jobs/urls.py
from django.urls import path
from . import views

app_name = 'jobs'
urlpatterns = [
    path('', views.index, name='index'),
    path('<id>/', views.detail, name='detail'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

# static files
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jobs.urls', namespace='jobs')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobs/models.py
from django.db import models


class Job(models.Model):
    name = models.CharField(max_length=200)
    summary = models.CharField(max_length=200)
    image = models.ImageField(upload_to='images/')


    def __str__(self):
        return self.name

jobs/views.py
from django.shortcuts import render, get_object_or_404
from .models import Job



def index(request):
    queryset = Job.objects.all()   
    context = {
        'object_list': queryset
    }
    return render(request, 'jobs/index.html', context)

def detail(request, id):
    obj = get_object_or_404(Job, id=id)
    context = {
        'object': obj
    }
    return render(request, 'jobs/detail.html', context)

jobs/templates/jobs/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.1.1">
    <title>AZWRI</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/album/">

    <!-- Bootstrap core CSS -->
<link href="{% static 'bootstrap/css/bootstrap.min.css'%}" rel="stylesheet" >

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/4.5/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/4.5/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/4.5/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/4.5/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/4.5/assets/img/favicons/safari-pinned-tab.svg" color="#563d7c">
<link rel="icon" href="/docs/4.5/assets/img/favicons/favicon.ico">
<meta name="msapplication-config" content="/docs/4.5/assets/img/favicons/browserconfig.xml">
<meta name="theme-color" content="#563d7c">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <!-- <link href="album.css" rel="stylesheet"> -->
  </head>
  <body>



{% block content %}
  
{% endblock content %}


<footer class="text-muted">
    <div class="container">
      <p class="float-right">
        <a href="#">Back to top</a>
      </p>
      <p>Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
      <p>New to Bootstrap? <a href="https://getbootstrap.com/">Visit the homepage</a> or read our <a href="/docs/4.5/getting-started/introduction/">getting started guide</a>.</p>
    </div>
  </footer>
  <script src="{%static 'bootstrap/js/popper.min.js'%}"></script>
  <script src="{%static 'bootstrap/js/jquery-3.5.1.slim.min.js'%}"></script>
  <script src="{%static 'bootstrap/js/bootstrap.min.js'%}"></script>
</body>
  </html>

jobs/templates/jobs/detail.html
{% extends "jobs/base.html" %} {% load static %} {% block content %}

<div class="col-md-4">
  <div class="card mb-4 shadow-sm">
    <img src="{{ object.image.url }}" alt="image" width="100%" />
    <div class="card-body">
      <p class="card-text">{{ object.summary }}</p>
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          <button type="button" class="btn btn-sm btn-outline-secondary">
            View
          </button>
          <button type="button" class="btn btn-sm btn-outline-secondary">
            Edit
          </button>
        </div>
        <small class="text-muted">9 mins</small>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

jobs/templates/jobs/index.html
{% extends "jobs/base.html" %}
{% load static %}


{% block content %}
  

<main role="main">
    <section class="jumbotron text-center">
      <div class="container">
        <h1>AbdulRahman</h1>
        <p class="lead text-muted">Here you will find all my projects.</p>
        <p>
          <a href="mailto:aazwri@gmail.com" class="btn btn-primary my-2">Email me!</a>
          <a href="#" class="btn btn-secondary my-2">Secondary action</a>
        </p>
        <img src="{% static 'jobs/images/logo.jpg' %}" alt="logo" width="200px">
      </div>
    </section>
  
    <div class="album py-5 bg-light">
      <div class="container">
  
        <div class="row">

            {% for job in object_list %}
              
          <div class="col-md-4">
            <div class="card mb-4 shadow-sm">
              <a href="{% url 'jobs:detail' job.id %}">
                <img src="{{ job.image.url }}" alt="image" width="100%">
              </a>
              <div class="card-body">
                <p class="card-text">
                    {{ job.summary }}
                </p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                    <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                  </div>
                  <small class="text-muted">9 mins</small>
                </div>
              </div>
            </div>
          </div>

          {% endfor %}

        </div>
      </div>
    </div>
  </main>

  {% endblock content %}